// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Libra Seguros Tech"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/agents/case-events": {
            "post": {
                "description": "Called by Rachel after classifying an email. Requires X-Agent-Key header.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "Register a case event from an incoming email",
                "parameters": [
                    {
                        "description": "Case event payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCaseEventRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CaseEventResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "Authenticates a user and returns a JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Invalidates the session (client-side). JWT blacklist pending.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/case-events/approved": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all case events approved by a human reviewer (activity history).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "List approved case events",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.CaseEventResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/case-events/metrics": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns aggregated stats: total, approved, pending, processed, and last event timestamp.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "Get case event metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CaseEventMetrics"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/case-events/pending": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all case events not yet approved by a human reviewer.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "List pending case events",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.CaseEventResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/case-events/{id}/review": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "A human reviewer approves Rachel's classification or corrects it with a comment.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "Approve or correct a case event classification",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Case event UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Review payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ReviewCaseEventRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CaseEventResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/cases": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a list of legal cases. Supports optional filtering by status, pipeline_stage, and case_type.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "List cases",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Case status (1=open, 2=closed, 3=suspended)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pipeline stage (ingesta, extraccion, triage, asignado, borrador, completado)",
                        "name": "pipeline_stage",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Case type (1=lawsuit, 2=mediation, 3=third_party)",
                        "name": "case_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.CaseResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/cases/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a single legal case with associated firm and user data.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cases"
                ],
                "summary": "Get case by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Case UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CaseResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/claims": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches claim from SISE and persists it in our DB. Idempotent by sise_claim_id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "claims"
                ],
                "summary": "Create a claim from SISE data",
                "parameters": [
                    {
                        "description": "Claim number",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "nro_stro": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.ClaimResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/claims/lookup": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches claim + policy + producer from SISE by claim number. Does not persist.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "claims"
                ],
                "summary": "Look up a claim in SISE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SISE claim number",
                        "name": "nro_stro",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ClaimLookupResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CaseEventMetrics": {
            "type": "object",
            "properties": {
                "approved": {
                    "type": "integer"
                },
                "last_event_at": {
                    "type": "string"
                },
                "pending": {
                    "type": "integer"
                },
                "processed": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.CaseEventResponse": {
            "type": "object",
            "properties": {
                "approved": {
                    "type": "boolean"
                },
                "case_id": {
                    "type": "string"
                },
                "confidence": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mail_id": {
                    "type": "string"
                },
                "mail_provider": {
                    "type": "string"
                },
                "mail_type": {
                    "type": "string"
                },
                "original_mail_type": {
                    "type": "string"
                },
                "processed": {
                    "type": "boolean"
                },
                "raw_caratula": {
                    "type": "string"
                },
                "raw_case_number": {
                    "type": "string"
                },
                "raw_claim_number": {
                    "type": "string"
                },
                "raw_policy": {
                    "type": "string"
                },
                "reasoning": {
                    "type": "string"
                },
                "received_at": {
                    "type": "string"
                },
                "review_comment": {
                    "type": "string"
                },
                "reviewed_at": {
                    "type": "string"
                },
                "reviewed_by": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "dto.CaseResponse": {
            "type": "object",
            "properties": {
                "action_type": {
                    "type": "string"
                },
                "assigned_user": {
                    "$ref": "#/definitions/dto.UserSummary"
                },
                "case_number": {
                    "type": "string"
                },
                "case_type": {
                    "type": "string"
                },
                "claim_number": {
                    "type": "string"
                },
                "court": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "defense_firm": {
                    "$ref": "#/definitions/dto.FirmSummary"
                },
                "estimated_amount": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "incident_date": {
                    "type": "string"
                },
                "opened_at": {
                    "type": "string"
                },
                "pipeline_stage": {
                    "type": "string"
                },
                "plaintiff_firm": {
                    "$ref": "#/definitions/dto.FirmSummary"
                },
                "policy": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "tribunal": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.ClaimLookupResponse": {
            "type": "object",
            "properties": {
                "claim": {
                    "$ref": "#/definitions/sise.Claim"
                },
                "policy": {
                    "$ref": "#/definitions/sise.PolicySummary"
                },
                "producer": {
                    "$ref": "#/definitions/sise.Producer"
                }
            }
        },
        "dto.ClaimResponse": {
            "type": "object",
            "properties": {
                "cause": {
                    "type": "string"
                },
                "claim_number": {
                    "type": "integer"
                },
                "claim_subnumber": {
                    "type": "integer"
                },
                "commercial_product": {
                    "type": "string"
                },
                "commercial_product_code": {
                    "type": "integer"
                },
                "contratante": {
                    "type": "string"
                },
                "coverage": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "doc_number": {
                    "type": "string"
                },
                "doc_type": {
                    "type": "string"
                },
                "estimated_amount": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "incident_date": {
                    "type": "string"
                },
                "insured_amount": {
                    "type": "number"
                },
                "notice_date": {
                    "type": "string"
                },
                "paid_amount": {
                    "type": "number"
                },
                "payment_date": {
                    "type": "string"
                },
                "policy_endorsement": {
                    "type": "integer"
                },
                "policy_number": {
                    "type": "integer"
                },
                "policy_type": {
                    "type": "string"
                },
                "policy_valid_from": {
                    "type": "string"
                },
                "policy_valid_to": {
                    "type": "string"
                },
                "producer_code": {
                    "type": "integer"
                },
                "producer_group_code": {
                    "type": "integer"
                },
                "producer_name": {
                    "type": "string"
                },
                "producer_status": {
                    "type": "string"
                },
                "producer_type": {
                    "type": "string"
                },
                "producer_type_code": {
                    "type": "integer"
                },
                "ramo_code": {
                    "type": "integer"
                },
                "registration_date": {
                    "type": "string"
                },
                "sise_claim_id": {
                    "type": "integer"
                },
                "sise_id_pv": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.CreateCaseEventRequest": {
            "type": "object",
            "required": [
                "confidence",
                "mail_id",
                "mail_type",
                "received_at"
            ],
            "properties": {
                "confidence": {
                    "type": "number",
                    "maximum": 1,
                    "minimum": 0
                },
                "mail_id": {
                    "type": "string"
                },
                "mail_provider": {
                    "type": "string"
                },
                "mail_type": {
                    "type": "integer",
                    "maximum": 7,
                    "minimum": 1
                },
                "raw_caratula": {
                    "type": "string"
                },
                "raw_case_number": {
                    "type": "string"
                },
                "raw_claim_number": {
                    "description": "Raw identifiers extracted from the mail (unnormalized)",
                    "type": "string"
                },
                "raw_policy": {
                    "type": "string"
                },
                "reasoning": {
                    "type": "string"
                },
                "received_at": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "dto.FirmSummary": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dto.UserInfo"
                }
            }
        },
        "dto.ReviewCaseEventRequest": {
            "type": "object",
            "properties": {
                "mail_type": {
                    "description": "if nil, approves Rachel's classification as-is",
                    "type": "integer"
                },
                "review_comment": {
                    "description": "required when changing mail_type",
                    "type": "string"
                }
            }
        },
        "dto.UserInfo": {
            "type": "object",
            "properties": {
                "capabilities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "dto.UserSummary": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                }
            }
        },
        "sise.Claim": {
            "type": "object",
            "properties": {
                "causa": {
                    "type": "string"
                },
                "cobertura": {
                    "type": "string"
                },
                "codigo_ramo": {
                    "type": "number"
                },
                "contratante_pagador": {
                    "type": "string"
                },
                "diagnostico": {
                    "type": "string"
                },
                "estado": {
                    "type": "string"
                },
                "fecha_aviso": {
                    "type": "string"
                },
                "fecha_incurrido": {
                    "type": "string"
                },
                "fecha_pago": {
                    "type": "string"
                },
                "fecha_resgistro": {
                    "description": "typo is SISE's own",
                    "type": "string"
                },
                "id_pv": {
                    "type": "integer"
                },
                "id_stro": {
                    "type": "integer"
                },
                "importe_estimado": {
                    "type": "number"
                },
                "importe_pago": {
                    "type": "number"
                },
                "nro_endoso": {
                    "type": "number"
                },
                "nro_poliza": {
                    "type": "number"
                },
                "nro_siniestro": {
                    "type": "integer"
                },
                "nro_subreclamo": {
                    "type": "integer"
                },
                "paciente": {
                    "type": "string"
                },
                "parentesco": {
                    "type": "string"
                },
                "titular": {
                    "type": "string"
                },
                "tomador_doc": {
                    "type": "string"
                },
                "tomador_tipo_doc": {
                    "type": "string"
                }
            }
        },
        "sise.PolicySummary": {
            "type": "object",
            "properties": {
                "Autoadministrada": {
                    "type": "number"
                },
                "Codido_Asegurado": {
                    "description": "typo is SISE's own",
                    "type": "number"
                },
                "Codigo_Productor": {
                    "type": "number"
                },
                "Codigo_Ramo": {
                    "type": "number"
                },
                "Codigo_Sucursal": {
                    "type": "number"
                },
                "Contratante": {
                    "type": "string"
                },
                "Estado": {
                    "type": "string"
                },
                "Fecha_Emision": {
                    "type": "string"
                },
                "Id_pv": {
                    "type": "number"
                },
                "Moneda": {
                    "type": "string"
                },
                "Nombre_o_Razon_Social_Productor": {
                    "type": "string"
                },
                "Numero_Documento": {
                    "type": "string"
                },
                "Numero_Endoso": {
                    "type": "number"
                },
                "Numero_Poliza": {
                    "type": "number"
                },
                "Premio": {
                    "type": "number"
                },
                "Prima": {
                    "type": "number"
                },
                "Producto_comercial": {
                    "type": "string"
                },
                "Ramo": {
                    "type": "string"
                },
                "Sucursal": {
                    "type": "string"
                },
                "Suma_Asegurada": {
                    "type": "number"
                },
                "Tipo_Documento": {
                    "type": "string"
                },
                "Tipo_de_Poliza": {
                    "type": "string"
                },
                "Vigencia_Desde": {
                    "type": "string"
                },
                "Vigencia_Hasta": {
                    "type": "string"
                },
                "cant_items": {
                    "type": "number"
                },
                "cantidad_siniestros": {
                    "type": "number"
                },
                "cod_producto_com": {
                    "type": "number"
                },
                "conducto": {
                    "type": "string"
                },
                "tarjeta_cbu": {
                    "type": "string"
                },
                "telefono_tomador": {
                    "type": "string"
                },
                "tipo_conducto": {
                    "type": "string"
                }
            }
        },
        "sise.Producer": {
            "type": "object",
            "properties": {
                "cod_agente": {
                    "type": "number"
                },
                "cod_baja": {
                    "type": "number"
                },
                "cod_estado": {
                    "type": "string"
                },
                "cod_grupo": {
                    "type": "number"
                },
                "cod_tipo_agente": {
                    "type": "number"
                },
                "fec_baja": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                },
                "tipo_agente": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and the JWT token",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Libra Legal API",
	Description:      "Backend service for Libra Legal AI — legal case management platform",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
